//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiRentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaAlquiler
    {
        public int IdLinea { get; set; }
        public int IdAlquiler { get; set; }
        public int IdMaterial { get; set; }
        public decimal PrecioDiaAplicado { get; set; }
        public int Dias { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    
        public virtual Alquiler Alquiler { get; set; }
        public virtual Material Material { get; set; }
    }
}
