var searchData=
[
  ['cachedcrmaterial_0',['CachedCrMaterial',['../class_ski_rent_informes_1_1_cached_cr_material.html',1,'SkiRentInformes']]],
  ['cachedcrmaterialestado_1',['CachedCrMaterialEstado',['../class_ski_rent_informes_1_1_cached_cr_material_estado.html',1,'SkiRentInformes']]],
  ['cachedcrreservacliente_2',['CachedCrReservaCliente',['../class_ski_rent_informes_1_1_cached_cr_reserva_cliente.html',1,'SkiRentInformes']]],
  ['cachedcrystalreport1_3',['CachedCrystalReport1',['../classtest_a_p_i_s_1_1_cached_crystal_report1.html',1,'testAPIS']]],
  ['cantidad_4',['Cantidad',['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_cliente_a_p_i.html#a823b7d74c67e83ee3a6d1ebd81c11bf8',1,'Proyecto_WPF_SkiRent.Controllers.ClienteAPI.Cantidad()'],['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_material_a_p_i.html#a760a192d61977d9f4b2f69ca369d3a6b',1,'Proyecto_WPF_SkiRent.Controllers.MaterialAPI.Cantidad()'],['../class_ski_rent_model_1_1_repos_1_1_cliente_repo.html#a55d734b292fb1797db5d141176028c20',1,'SkiRentModel.Repos.ClienteRepo.Cantidad()'],['../class_ski_rent_model_1_1_repos_1_1_material_repo.html#a14266af1fb7f69f37789cc9baed0e054',1,'SkiRentModel.Repos.MaterialRepo.Cantidad()']]],
  ['cantidadactivos_5',['CantidadActivos',['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_alquiler_a_p_i.html#a3f43a8102cb5eeae66cf20b7ac100431',1,'Proyecto_WPF_SkiRent.Controllers.AlquilerAPI.CantidadActivos()'],['../class_ski_rent_model_1_1_repos_1_1_alquiler_repo.html#abdf5210006b163c611d1420610d312b7',1,'SkiRentModel.Repos.AlquilerRepo.CantidadActivos()']]],
  ['categoriaapi_6',['CategoriaAPI',['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_categoria_a_p_i.html',1,'Proyecto_WPF_SkiRent::Controllers']]],
  ['categoriamaterial_7',['CategoriaMaterial',['../class_ski_rent_model_1_1_categoria_material.html',1,'SkiRentModel']]],
  ['categoriamaterialwindow_8',['CategoriaMaterialWindow',['../class_proyecto___w_p_f___ski_rent_1_1_categoria_material_window.html',1,'Proyecto_WPF_SkiRent']]],
  ['categoriarepo_9',['CategoriaRepo',['../class_ski_rent_model_1_1_repos_1_1_categoria_repo.html',1,'SkiRentModel::Repos']]],
  ['circuitdto_10',['CircuitDto',['../class_a_p_i_s___test_1_1_dtos_1_1_circuit_dto.html',1,'APIS_Test::Dtos']]],
  ['circuito_11',['Circuito',['../class_a_p_i_s___test_1_1_models_1_1_circuito.html',1,'APIS_Test::Models']]],
  ['class1_12',['Class1',['../class_model_1_1_class1.html',1,'Model']]],
  ['cliente_13',['Cliente',['../class_ski_rent_model_1_1_cliente.html',1,'SkiRentModel']]],
  ['clienteapi_14',['ClienteAPI',['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_cliente_a_p_i.html',1,'Proyecto_WPF_SkiRent::Controllers']]],
  ['clienterepo_15',['ClienteRepo',['../class_ski_rent_model_1_1_repos_1_1_cliente_repo.html',1,'SkiRentModel::Repos']]],
  ['com_20jamesnk_20newtonsoft_20json_20master_20doc_20icons_20logo_20jpg_20json_20net_16',['![Logo](&lt;a href=&quot;https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Doc/icons/logo.jpg&quot;&gt;https://raw.githubusercontent.com/JamesNK/Newtonsoft.Json/master/Doc/icons/logo.jpg&lt;/a&gt;) Json.NET',['../dir_f6e76525f7e6a12e3a7ebf57177ec624.html#autotoc_md0',1,'']]],
  ['competitordto_17',['CompetitorDto',['../class_a_p_i_s___test_1_1_dtos_1_1_competitor_dto.html',1,'APIS_Test::Dtos']]],
  ['competitorprofiledto_18',['CompetitorProfileDto',['../class_a_p_i_s___test_1_1_dtos_1_1_competitor_profile_dto.html',1,'APIS_Test::Dtos']]],
  ['core_19',['Entity Framework Core',['../dir_2e57c9440fadb34d94cbe1e3411971db.html#autotoc_md7',1,'']]],
  ['crear_20',['Crear',['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_alquiler_a_p_i.html#ab5931f081f4154659ea59cb6ce9cf018',1,'Proyecto_WPF_SkiRent.Controllers.AlquilerAPI.Crear()'],['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_categoria_a_p_i.html#ae61aa23821ec9c4b6c21a08f9d6da225',1,'Proyecto_WPF_SkiRent.Controllers.CategoriaAPI.Crear()'],['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_cliente_a_p_i.html#ae9dd7e15ad7dde3659cf4fb24109534b',1,'Proyecto_WPF_SkiRent.Controllers.ClienteAPI.Crear()'],['../class_proyecto___w_p_f___ski_rent_1_1_controllers_1_1_material_a_p_i.html#aca8b3ffa820047d361095b518a71d2cd',1,'Proyecto_WPF_SkiRent.Controllers.MaterialAPI.Crear()']]],
  ['crmaterial_21',['CrMaterial',['../class_ski_rent_informes_1_1_cr_material.html',1,'SkiRentInformes']]],
  ['crmaterialestado_22',['CrMaterialEstado',['../class_ski_rent_informes_1_1_cr_material_estado.html',1,'SkiRentInformes']]],
  ['crreservacliente_23',['CrReservaCliente',['../class_ski_rent_informes_1_1_cr_reserva_cliente.html',1,'SkiRentInformes']]],
  ['crystalreport1_24',['CrystalReport1',['../classtest_a_p_i_s_1_1_crystal_report1.html',1,'testAPIS']]]
];
